import * as fs from 'fs';
import * as path from 'path';
import { generateEnvConfigTemplate } from '../core/formatter';

/**
 * Initialize smart-env in a project
 * Creates .env.example and env.config.ts
 */
export function initCommand(options: { force?: boolean } = {}): void {
  const cwd = process.cwd();

  console.log('🚀 Initializing smart-env...\n');

  // Create env.config.ts
  const configPath = path.join(cwd, 'env.config.ts');
  if (fs.existsSync(configPath) && !options.force) {
    console.log('⚠️  env.config.ts already exists. Use --force to overwrite.');
  } else {
    const configContent = generateEnvConfigTemplate();
    fs.writeFileSync(configPath, configContent, 'utf-8');
    console.log('✔ Created env.config.ts');
  }

  // Create .env.example
  const envExamplePath = path.join(cwd, '.env.example');
  if (fs.existsSync(envExamplePath) && !options.force) {
    console.log('⚠️  .env.example already exists. Use --force to overwrite.');
  } else {
    // Generate example from default template
    const exampleContent = `# Environment Variables Configuration
# Generated by smart-env

# Application environment
# Type: enum (development | production | test)
# Required
NODE_ENV=development

# Server port number
# Type: number
# Optional
# Default: 3000
PORT=3000

# Database connection URL
# Type: URL
# Required
DATABASE_URL=

# API authentication key
# Type: string
# Required
API_KEY=

# Enable debug mode
# Type: boolean (true/false, 1/0, yes/no)
# Optional
# Default: false
DEBUG=false
`;
    fs.writeFileSync(envExamplePath, exampleContent, 'utf-8');
    console.log('✔ Created .env.example');
  }

  // Check if .env exists, if not create it from example
  const envPath = path.join(cwd, '.env');
  if (!fs.existsSync(envPath)) {
    const envExampleContent = fs.readFileSync(envExamplePath, 'utf-8');
    fs.writeFileSync(envPath, envExampleContent, 'utf-8');
    console.log('✔ Created .env (copied from .env.example)');
  }

  console.log('\n✨ Initialization complete!');
  console.log('\nNext steps:');
  console.log('1. Edit env.config.ts to define your environment schema');
  console.log('2. Update .env with your actual values');
  console.log('3. Run "npx smart-env validate" to verify your configuration');
  console.log('4. Import and use: import { env } from "./env.config"');
}

/**
 * Scan the project for process.env usage
 */
export function scanProject(): string[] {
  const found = new Set<string>();
  const cwd = process.cwd();

  function scanFile(filePath: string): void {
    try {
      const content = fs.readFileSync(filePath, 'utf-8');
      const regex = /process\.env\.(\w+)/g;
      let match;

      while ((match = regex.exec(content)) !== null) {
        found.add(match[1]);
      }
    } catch (error) {
      // Skip files that can't be read
    }
  }

  function scanDirectory(dir: string): void {
    try {
      const entries = fs.readdirSync(dir, { withFileTypes: true });

      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);

        // Skip node_modules and other common directories
        if (entry.isDirectory()) {
          if (!['node_modules', '.git', 'dist', 'build', '.next'].includes(entry.name)) {
            scanDirectory(fullPath);
          }
        } else if (entry.isFile()) {
          const ext = path.extname(entry.name);
          if (['.js', '.ts', '.jsx', '.tsx', '.mjs', '.cjs'].includes(ext)) {
            scanFile(fullPath);
          }
        }
      }
    } catch (error) {
      // Skip directories that can't be read
    }
  }

  scanDirectory(cwd);
  return Array.from(found).sort();
}

/**
 * Scan command: find all process.env usage in the project
 */
export function scanCommand(): void {
  console.log('🔍 Scanning project for environment variable usage...\n');

  const variables = scanProject();

  if (variables.length === 0) {
    console.log('No environment variables found in the project.');
    return;
  }

  console.log(`Found ${variables.length} environment variable(s):\n`);

  variables.forEach((varName) => {
    console.log(`  • ${varName}`);
  });

  console.log('\n💡 Tip: Add these variables to your env.config.ts');
}
